In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import plotly.express as px
from scipy.stats import kruskal
df = pd.read_csv(r"MSAR_Table.csv")

In [ ]:
df = pd.read_csv(r"MSAR_Table.csv")
test = df.groupby(["Course"]).size().reset_index(name = "count").sort_values("count", ascending = False)
test = test.reset_index(drop = True)
for index, row in df.iterrows():
    if row["Course"] == 'Biochemistry':
        df.loc[index, "Class"] = "BCHM"
    if row["Course"] == 'Physical Chemistry':
        df.loc[index, "Class"] = "PCHM"
    if row["Course"] == 'Organic Chemistry':
        df.loc[index, "Class"] = "ORGO"
    if row["Course"] == 'Statistics' or row["Course"] == 'Biostatistics': #
        df.loc[index, "Class"] = "STAT"
    if row["Course"] == 'Psychology' or row["Course"] == 'Sociology':
        df.loc[index, "Class"] = "PSYC"
state_map = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DC" : "District of Columbia",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "PR" : "Puerto Rico",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
    "QC" : "Quebec",
    "ON" : "Ontario",
    "MB" : "Manitoba",
    "BC" : "British Columbia"
}
df["State"] = df["State"].map(state_map)
df

,State,Medical School,Course,Class,Required or Recommended?,Additional Info,Credit Hours,Lab?,Pass/Fail,AP Credit,Online Course,Community College
0,Alabama,Frederick P. Whiddon College of Medicine at th...,Anthropology,BESS,Required,Anthropology or any of the Behavioral and Soci...,6.0,-1,0,0.0,1.0,1.0
1,Alabama,Frederick P. Whiddon College of Medicine at th...,Biochemistry,BCHM,Recommended,Biochemistry may take the place of Organic Che...,NaN,1,0,-1.0,0.0,1.0
2,Alabama,Frederick P. Whiddon College of Medicine at th...,Biology,BIOL,Required,NaN,8.0,1,0,0.0,0.0,1.0
3,Alabama,Frederick P. Whiddon College of Medicine at th...,Chemistry,CHEM,Required,General Chemistry,8.0,1,0,0.0,0.0,1.0
4,Alabama,Frederick P. Whiddon College of Medicine at th...,Composition & Rhetoric,ENGL,Required,English Literature may be used in place of a p...,6.0,-1,0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1165,Quebec,Universite de Montreal Faculty of Medicine,Physics,PHYS,Required,NaN,NaN,1,1,1.0,1.0,1.0
1166,Quebec,Universite de Sherbrooke Faculty of Medicine,Biology,BIOL,Required,Biologie NYA Évolution et diversité du vivant...,NaN,1,0,0.0,0.0,0.0
1167,Quebec,Universite de Sherbrooke Faculty of Medicine,Cell Biology,BIOL,Required,Biologie 401 Organismes pluricellulaires (OOX...,NaN,1,0,0.0,0.0,0.0
1168,Quebec,Universite de Sherbrooke Faculty of Medicine,Chemistry,CHEM,Required,3 (TROIS) COURS DEMANDÉSChimie NYA Chimie gén...,NaN,1,0,0.0,0.0,0.0
1169,Quebec,Universite de Sherbrooke Faculty of Medicine,Physics,PHYS,Required,3 (TROIS) COURS DEMANDÉSPhysique NYA Mécaniqu...,NaN,1,0,0.0,0.0,0.0

In [42]:
classes = df["Class"].unique().tolist()
ratios = []
for course in classes:
    tempdf = df[df["Class"] == course]
    good = tempdf[tempdf["Online Course"] == 1]["Online Course"].count()
    bad = tempdf[tempdf["Online Course"] == -1]["Online Course"].count()
    case = tempdf[tempdf["Online Course"] == 0]["Online Course"].count()
    print("class:", course)
    print("good count:", good)
    print("bad count:", bad)
    print("case-by-case count:", case)
    print(f"good ratio: {good/(tempdf["Online Course"].count()):.3f}")
    print(f"bad ratio: {bad/(tempdf["Online Course"].count()):.3f}")
    print(f"case-by-case ratio: {case/(tempdf["Online Course"].count()):.3f}")
    ratios.append(case/(tempdf["Online Course"].count()))
    print("")
ratios
h, p = kruskal(0.1544, 0.251, 0.271, 0.1485, 0.2279, 0.260)
print(p)

class: BESS
good count: 102
bad count: 13
case-by-case count: 21
good ratio: 0.750
bad ratio: 0.096
case-by-case ratio: 0.154

class: CHEM
good count: 173
bad count: 62
case-by-case count: 79
good ratio: 0.551
bad ratio: 0.197
case-by-case ratio: 0.252

class: BIOL
good count: 200
bad count: 47
case-by-case count: 92
good ratio: 0.590
bad ratio: 0.139
case-by-case ratio: 0.271

class: ENGL
good count: 71
bad count: 15
case-by-case count: 15
good ratio: 0.703
bad ratio: 0.149
case-by-case ratio: 0.149

class: MATH
good count: 94
bad count: 11
case-by-case count: 31
good ratio: 0.691
bad ratio: 0.081
case-by-case ratio: 0.228

class: PHYS
good count: 84
bad count: 21
case-by-case count: 37
good ratio: 0.592
bad ratio: 0.148
case-by-case ratio: 0.261

0.41588018699550794

In [5]:
bchm = df[(df["Course"] == "Biochemistry")]
bchm1 = bchm.groupby(["State", "Online Course"]).size().reset_index(name = "count")
for index, row in bchm1.iterrows():
    if row["Online Course"] == 0.0:
        bchm1.loc[index, "Online Course"] = "Case-by-case"
    if row["Online Course"] == 1.0:
        bchm1.loc[index, "Online Course"] = "Approved"
    if row["Online Course"] == -1.0:
        bchm1.loc[index, "Online Course"] = "Not approved"

pivot = bchm1.pivot(index="State", columns="Online Course", values="count").fillna(0)
pivot_masked = pivot.mask(pivot == 0)
fig = px.imshow(
    pivot_masked,
    aspect="auto",
    labels={"color": "Count"},
    title="Number of Medical Schools' Online Biochemistry Course Approval by State",
    color_continuous_scale="Plotly3"
)
 
fig.update_layout(width=800, height=900)

C:\Users\georg\AppData\Local\Temp\ipykernel_14588\3638303495.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Case-by-case' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  bchm1.loc[index, "Online Course"] = "Case-by-case"

In [5]:
import plotly.graph_objects as go



bchm = df[(df["Course"] == "Biochemistry")]
bchm1 = bchm.groupby(["State", "Community College"]).size().reset_index(name = "count")
bchm1

bchm1 = bchm1[bchm1["Community College"] == 1.0]
lookup = {
    "British Columbia": "Canada",
    "Manitoba": "Canada",
    "Ontario": "Canada",
    "Quebec": "Canada",
    "Puerto Rico": "Puerto Rico"
}

bchm1["Country"] = bchm1["State"].map(lookup).fillna("USA")

bchm1.to_csv("counts_state_cc.csv")
bchm1

                   State  Community College  count      Country
0                Alabama                1.0      2          USA
1                Arizona                1.0      2          USA
2               Arkansas                1.0      1          USA
3       British Columbia                1.0      1       Canada
4             California                1.0      8          USA
5            Connecticut                1.0      1          USA
7   District of Columbia                1.0      2          USA
10               Florida                1.0      6          USA
11               Georgia                1.0      2          USA
12                Hawaii                1.0      1          USA
15              Illinois                1.0      4          USA
16               Indiana                1.0      1          USA
17                  Iowa                1.0      1          USA
18                Kansas                1.0      1          USA
19              Kentucky                1.0      1          USA
21             Louisiana                1.0      2          USA
23              Maryland                1.0      3          USA
24         Massachusetts                1.0      2          USA
25              Michigan                1.0      4          USA
26             Minnesota                1.0      1          USA
28              Missouri                1.0      1          USA
29              Nebraska                1.0      2          USA
30                Nevada                1.0      3          USA
31         New Hampshire                1.0      1          USA
33            New Jersey                1.0      2          USA
36              New York                1.0      6          USA
38        North Carolina                1.0      2          USA
39          North Dakota                1.0      1          USA
41                  Ohio                1.0      4          USA
42              Oklahoma                1.0      1          USA
45          Pennsylvania                1.0      6          USA
47           Puerto Rico                1.0      1  Puerto Rico
48                Quebec                1.0      1       Canada
49          Rhode Island                1.0      1          USA
51        South Carolina                1.0      2          USA
52          South Dakota                1.0      1          USA
54             Tennessee                1.0      2          USA
56                 Texas                1.0     10          USA
59              Virginia                1.0      3          USA
60            Washington                1.0      1          USA
61         West Virginia                1.0      2          USA
62             Wisconsin                1.0      2          USA

In [10]:
bchm1 = bchm.groupby(["Community College"]).size().reset_index(name = "count")
bchm1["percentage"] = bchm1["count"]/128 * 100
bchm1
# ----
bchm[bchm["Online Course"] == -1]

,State,Medical School,Course,Class,Required or Recommended?,Additional Info,Credit Hours,Lab?,Pass/Fail,AP Credit,Online Course,Community College
47,CA,California Northstate University College of Me...,Biochemistry,CHEM,Required,"1 semester, 1 quarter, or 3 units of Biochemistry",3.0,-1,-1,-1.0,-1.0,1.0
146,DC,George Washington University School of Medicin...,Biochemistry,CHEM,Recommended,Inorganic chemistry recommended. Online for F...,4.0,1,-1,-1.0,-1.0,-1.0
167,FL,Charles E. Schmidt College of Medicine at Flor...,Biochemistry,CHEM,Recommended,Biochemistry is strongly recommended. One seme...,4.0,1,-1,-1.0,-1.0,1.0
497,MS,University of Mississippi School of Medicine,Biochemistry,CHEM,Required,NaN,3.0,-1,-1,-1.0,-1.0,-1.0
503,NC,Brody School of Medicine at East Carolina Univ...,Biochemistry,CHEM,Required,NaN,3.0,-1,-1,-1.0,-1.0,1.0
510,NC,Duke University School of Medicine,Biochemistry,CHEM,Recommended,NaN,NaN,-1,-1,1.0,-1.0,-1.0
558,NJ,Cooper Medical School of Rowan University,Biochemistry,CHEM,Recommended,NaN,NaN,-1,-1,-1.0,-1.0,-1.0
577,NJ,Rutgers New Jersey Medical School,Biochemistry,CHEM,Required,Biochemistry,3.0,-1,-1,-1.0,-1.0,-1.0
632,NY,Donald and Barbara Zucker School of Medicine a...,Biochemistry,CHEM,Recommended,NaN,4.0,1,-1,-1.0,-1.0,0.0
657,NY,New York Medical College,Biochemistry,CHEM,Required,1 semester with or without lab (or equivalent),4.0,1,-1,1.0,-1.0,1.0
662,NY,NYU Grossman Long Island School of Medicine,Biochemistry,CHEM,Recommended,NaN,NaN,1,-1,-1.0,-1.0,1.0
690,NY,State University of New York Upstate Medical U...,Biochemistry,CHEM,Required,NaN,3.0,-1,0,1.0,-1.0,1.0
703,NY,University of Rochester School of Medicine and...,Biochemistry,CHEM,Recommended,NaN,NaN,-1,-1,-1.0,-1.0,1.0
752,OH,Wright State University Boonshoft School of Me...,Biochemistry,CHEM,Required,One semester or two quarters of Biochemstry is...,3.0,-1,1,0.0,-1.0,1.0
772,PA,Geisinger Commonwealth School of Medicine,Biochemistry,CHEM,Recommended,NaN,4.0,1,-1,1.0,-1.0,1.0
773,PA,Geisinger Commonwealth School of Medicine,Biochemistry,CHEM,Required,2 semesters each of organic chemistry with lab...,8.0,1,-1,1.0,-1.0,1.0
835,PR,San Juan Bautista School of Medicine,Biochemistry,CHEM,Recommended,NaN,3.0,-1,-1,-1.0,-1.0,-1.0
844,PR,Universidad Central del Caribe School of Medicine,Biochemistry,CHEM,Recommended,NaN,NaN,-1,-1,-1.0,-1.0,1.0
863,RI,The Warren Alpert Medical School of Brown Univ...,Biochemistry,CHEM,Required,One course in Biochemistry with lab is required.,NaN,1,-1,-1.0,-1.0,1.0
913,TN,Meharry Medical College,Biochemistry,CHEM,Required,One semester of Biochemistry. If course is ta...,3.0,-1,-1,-1.0,-1.0,-1.0
952,TX,Texas A&M University School of Medicine,Biochemistry,CHEM,Required,Biochemistry I. Rigorous treatment of the stru...,3.0,-1,-1,-1.0,-1.0,-1.0
1046,VA,Virginia Commonwealth University School of Med...,Biochemistry,CHEM,Required,NaN,3.0,-1,-1,-1.0,-1.0,1.0
1055,VA,Virginia Tech Carilion School of Medicine,Biochemistry,CHEM,Required,Either 2 semesters of Organic Chemistry or 1 s...,8.0,1,0,0.0,-1.0,0.0
1105,WV,Marshall University Joan C. Edwards School of ...,Biochemistry,CHEM,Required,Biochemistry,3.0,-1,-1,1.0,-1.0,1.0

In [13]:
df.groupby("Medical School").size()

Medical School
Albany Medical College                                                3
Albert Einstein College of Medicine                                   9
Alice L. Walton School of Medicine                                   13
Anne Burnett Marion School of Medicine at TCU                         4
Baylor College of Medicine                                            7
                                                                     ..
Weill Cornell Medicine                                                4
West Virginia University School of Medicine                          13
Western Michigan University Homer Stryker M.D. School of Medicine    12
Wright State University Boonshoft School of Medicine                  6
Yale School of Medicine                                               3
Length: 164, dtype: int64